trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.302'

  - script: |
      dotnet build --configuration Release
    displayName: 'Build project'